In [ ]:
# O objetivo aqui vai ser arrumar os dados para backtest

In [1]:
import pandas as pd
import numpy as np

In [2]:
ta_ati = pd.read_excel('../../data/economatica_1/total_assets_mensal_ativas.xlsx',
                            skiprows = [1,2],
                            header=1,
                            index_col = 0,
                            na_values='-')
ta_can = pd.read_excel('../../data/economatica_1/total_assets_mensal_canceladas.xlsx',
                            skiprows = [1,2],
                            header=1,
                            index_col = 0,
                            na_values='-')
# ta.can = ta_can(["Jan-86", "Feb-86"]) # assim não precisaria de inplace
ta_can.drop(["Jan-86", "Feb-86"], inplace=True) # para ficar igual a index de ta_ati

# tudo sobre merging de dataframes
# https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
# checar se dois index são iguais
# https://www.geeksforgeeks.org/python-pandas-index-equals/
# ta_ati.index.equals(ta_can.index) # retorna falso pois cancelados começa em janeiro de 86 e ativos começa em jan
# tot_ass.loc["Jan-86"]
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html
tot_ass = pd.concat([ta_ati,ta_can],axis=1,sort=False)
# len(ta_ati.columns)
# ta_can.shape

In [3]:
tickers = tot_ass.columns.str.extract('(.*)$')[0]
tot_ass.columns = tickers
# https://www.debuggex.com/cheatsheet/regex/python
# https://www.dataquest.io/blog/regex-cheatsheet/
on = tickers[tickers.str.contains('.\D3$')]
pn = tickers[tickers.str.contains('.\D4$')]
sto_tick = pd.concat([on, pn], ignore_index=True)
tot_ass = tot_ass[sto_tick]
tot_ass = tot_ass[tot_ass.index.str.contains("Mar|Jun|Sep|Dec")]
tot_ass.columns.name = "ticker"

In [32]:
# remover colums e row with NA de um dataframe é bem fácil
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html
stocks = tot_ass.loc["Dec-98":"Sep-19"]
stocks = stocks.dropna(axis="columns")

In [33]:
stocks

ticker,ABEV3,CBEE3,CEPE3,CEEB3,COCE3,CALI3,EKTR3,ELPL3,FNCN3,PETR3,WEGE3,EBEN3,CALI4,EKTR4,PETR4,AMBV4,EBEN4,ELPL4,WEGE4
Date,,,,,,,,,,,,,,,,,,,
Dec-98,4669322.0,2077201.0,1117173.0,2335287.0,963761.0,15145.0,2649971.0,7489679.0,16887.0,40098998.0,778197.0,2308292.0,15145.0,2649971.0,40098998.0,4669322.0,2308292.0,7489679.0,778197.0
Mar-99,5081862.0,2511723.0,1152644.0,2415828.0,972003.0,17597.0,2593481.0,8027848.0,17427.0,44125962.0,916114.0,2440568.0,17597.0,2593481.0,44125962.0,5081862.0,2440568.0,8027848.0,916114.0
Jun-99,4912526.0,2547084.0,1166655.0,2428266.0,1000528.0,17843.0,2683216.0,8284691.0,16031.0,45214963.0,975389.0,2471252.0,17843.0,2683216.0,45214963.0,4912526.0,2471252.0,8284691.0,975389.0
Sep-99,5138619.0,2407694.0,1208907.0,2471114.0,1798899.0,17789.0,2722677.0,8513419.0,16253.0,55392602.0,980402.0,2605481.0,17789.0,2722677.0,55392602.0,5138619.0,2605481.0,8513419.0,980402.0
Dec-99,9120614.0,2377607.0,1193975.0,2564845.0,1767608.0,17320.0,2698865.0,8304694.0,17338.0,56652644.0,939772.0,2541334.0,17320.0,2698865.0,56652644.0,9120614.0,2541334.0,8304694.0,939772.0
Mar-00,5296482.0,2457569.0,1180005.0,2586635.0,1773462.0,18513.0,2708649.0,8498748.0,17016.0,58451873.0,958553.0,2567792.0,18513.0,2708649.0,58451873.0,5296482.0,2567792.0,8498748.0,958553.0
Jun-00,5404446.0,2463739.0,1159088.0,3070363.0,1811758.0,21756.0,2682863.0,8548939.0,18206.0,59989655.0,1025812.0,2573963.0,21756.0,2682863.0,59989655.0,5404446.0,2573963.0,8548939.0,1025812.0
Sep-00,8243659.0,2481981.0,1162592.0,3167401.0,1846657.0,21473.0,2719899.0,8971927.0,22194.0,62860797.0,1043668.0,2689471.0,21473.0,2719899.0,62860797.0,8243659.0,2689471.0,8971927.0,1043668.0
Dec-00,8639652.0,2782303.0,1185126.0,3355987.0,1888875.0,25227.0,2776374.0,8807838.0,21795.0,66979136.0,1196710.0,2632698.0,25227.0,2776374.0,66979136.0,8639652.0,2632698.0,8807838.0,1196710.0
Mar-01,8732782.0,3021501.0,1169586.0,3440273.0,1931693.0,24982.0,2739899.0,9406427.0,22376.0,69520165.0,1183827.0,2715441.0,24982.0,2739899.0,69520165.0,8732782.0,2715441.0,9406427.0,1183827.0
Jun-01,8933278.0,3126553.0,1192962.0,3409553.0,2009630.0,26812.0,2772303.0,9707764.0,21917.0,71374378.0,1295227.0,2819018.0,26812.0,2772303.0,71374378.0,8933278.0,2819018.0,9707764.0,1295227.0
Sep-01,10174778.0,3199459.0,1867096.0,3560956.0,2063275.0,26923.0,2827224.0,10483335.0,22535.0,77173240.0,1404231.0,3177054.0,26923.0,2827224.0,77173240.0,10174778.0,3177054.0,10483335.0,1404231.0
Dec-01,11028812.0,3545988.0,2160807.0,3575691.0,2344499.0,33384.0,3215074.0,11475694.0,22999.0,75158596.0,1318607.0,1898500.0,33384.0,3215074.0,75158596.0,11028812.0,1898500.0,11475694.0,1318607.0
Mar-02,10356653.0,3596076.0,2404664.0,3628611.0,2228778.0,31726.0,3340853.0,11712355.0,23182.0,75293620.0,1262653.0,2014075.0,31726.0,3340853.0,75293620.0,10356653.0,2014075.0,11712355.0,1262653.0
Jun-02,11411848.0,3876025.0,2418041.0,3717813.0,2338549.0,36072.0,3249671.0,12040008.0,23599.0,80385270.0,1344981.0,2049095.0,36072.0,3249671.0,80385270.0,11411848.0,2049095.0,12040008.0,1344981.0
Sep-02,12887202.0,4304614.0,2499405.0,3842195.0,2629138.0,37080.0,3344279.0,13780309.0,23577.0,94797320.0,1648848.0,2114613.0,37080.0,3344279.0,94797320.0,12887202.0,2114613.0,13780309.0,1648848.0
Dec-02,12381406.0,4113867.0,2726459.0,4202435.0,2507458.0,41541.0,3250884.0,12951602.0,23637.0,97260082.0,1766747.0,2194068.0,41541.0,3250884.0,97260082.0,12381406.0,2194068.0,12951602.0,1766747.0
Mar-03,12705848.0,4112508.0,2682892.0,4063520.0,2484144.0,41760.0,3219901.0,12725647.0,24045.0,108466089.0,1719326.0,2167413.0,41760.0,3219901.0,108466089.0,12705848.0,2167413.0,12725647.0,1719326.0
Jun-03,11950246.0,4057513.0,2782781.0,4175960.0,2425924.0,42164.0,3243192.0,12488244.0,24579.0,118631625.0,1729949.0,2153417.0,42164.0,3243192.0,118631625.0,11950246.0,2153417.0,12488244.0,1729949.0
Sep-03,14253807.0,4020740.0,2805171.0,4088503.0,2454190.0,51740.0,3265682.0,12762101.0,24145.0,128472360.0,1782031.0,2139132.0,51740.0,3265682.0,128472360.0,14253807.0,2139132.0,12762101.0,1782031.0
Dec-03,14830119.0,4128018.0,2620422.0,4137830.0,2448007.0,49322.0,3476535.0,12723693.0,24453.0,136234363.0,1923291.0,2326579.0,49322.0,3476535.0,136234363.0,14830119.0,2326579.0,12723693.0,1923291.0
Mar-04,14201654.0,4224425.0,2742312.0,4170764.0,2473429.0,48044.0,3572673.0,12901124.0,23846.0,137476481.0,2030241.0,2348204.0,48044.0,3572673.0,137476481.0,14201654.0,2348204.0,12901124.0,2030241.0
Jun-04,14127407.0,4307637.0,2700550.0,4276287.0,2431352.0,45119.0,3638470.0,13066105.0,23600.0,141714160.0,2349070.0,2350891.0,45119.0,3638470.0,141714160.0,14127407.0,2350891.0,13066105.0,2349070.0
Sep-04,31774253.0,4443467.0,2763327.0,4118376.0,2400407.0,46351.0,3652537.0,13264904.0,23768.0,144745439.0,2403504.0,2403193.0,46351.0,3652537.0,144745439.0,31774253.0,2403193.0,13264904.0,2403504.0
Dec-04,33016564.0,4504071.0,2860542.0,4110225.0,2386481.0,77618.0,3450507.0,12855087.0,23893.0,147035117.0,2472599.0,2432826.0,77618.0,3450507.0,147035117.0,33016564.0,2432826.0,12855087.0,2472599.0
Mar-05,31242390.0,4795997.0,2948749.0,4507508.0,2435600.0,53289.0,3525948.0,12925610.0,23852.0,166645687.0,2636690.0,2426757.0,53289.0,3525948.0,166645687.0,31242390.0,2426757.0,12925610.0,2636690.0
Jun-05,30435834.0,4691699.0,3065488.0,4693009.0,2133867.0,53341.0,3310240.0,12966106.0,23291.0,165577252.0,2820894.0,2363497.0,53341.0,3310240.0,165577252.0,30435834.0,2363497.0,12966106.0,2820894.0
Sep-05,33055999.0,4747817.0,3047594.0,4748659.0,2192067.0,63977.0,3137706.0,12458860.0,23309.0,172160888.0,2934161.0,2326842.0,63977.0,3137706.0,172160888.0,33055999.0,2326842.0,12458860.0,2934161.0
Dec-05,33492833.0,4142898.0,3156281.0,4044038.0,2400409.0,78655.0,3394119.0,12377318.0,23643.0,183521108.0,3308637.0,2138645.0,78655.0,3394119.0,183521108.0,33492833.0,2138645.0,12377318.0,3308637.0
Mar-06,32286600.0,4162045.0,3209799.0,4084026.0,2424959.0,56663.0,3549608.0,11974020.0,23238.0,186031483.0,3353127.0,2137183.0,56663.0,3549608.0,186031483.0,32286600.0,2137183.0,11974020.0,3353127.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Jun-12,48521976.0,5167153.0,4079308.0,6567283.0,3489567.0,25469.0,4165281.0,10657072.0,29724.0,628027804.0,9109705.0,2430750.0,25469.0,4165281.0,628027804.0,48521976.0,2430750.0,10657072.0,9109705.0
Sep-12,49391546.0,4984794.0,3885347.0,6926716.0,3522595.0,26131.0,4526510.0,10619262.0,30681.0,646683148.0,8757033.0,2447503.0,26131.0,4526510.0,646683148.0,49391546.0,2447503.0,10619262.0,8757033.0
Dec-12,54159769.0,5229122.0,3870985.0,7107647.0,3560488.0,28943.0,4558718.0,10499218.0,30386.0,677716287.0,8873550.0,2511611.0,28943.0,4558718.0,677716287.0,54159769.0,2511611.0,10499218.0,8873550.0
Mar-13,48728570.0,5585535.0,3947603.0,7379790.0,3655643.0,17933.0,4678980.0,11346407.0,29583.0,695313138.0,9496435.0,2482832.0,17933.0,4678980.0,695313138.0,48728570.0,2482832.0,11346407.0,9496435.0
Jun-13,50982746.0,5311834.0,3804852.0,7026460.0,3575556.0,20399.0,4460114.0,11142402.0,29308.0,749027663.0,9542922.0,2500921.0,20399.0,4460114.0,749027663.0,50982746.0,2500921.0,11142402.0,9542922.0
Sep-13,51753315.0,5347243.0,3707916.0,6973082.0,3506336.0,25224.0,4336900.0,11031692.0,28700.0,758432791.0,9552065.0,2551574.0,25224.0,4336900.0,758432791.0,51753315.0,2551574.0,11031692.0,9552065.0
Dec-13,68674019.0,5712410.0,3791353.0,7627195.0,3371127.0,34572.0,4601380.0,10694051.0,28703.0,752966638.0,10141293.0,2457370.0,34572.0,4601380.0,752966638.0,68674019.0,2457370.0,10694051.0,10141293.0
Mar-14,63297044.0,6186288.0,3960323.0,7915354.0,3638038.0,32989.0,5151042.0,11243758.0,28701.0,802014652.0,9898693.0,2529293.0,32989.0,5151042.0,802014652.0,63297044.0,2529293.0,11243758.0,9898693.0
Jun-14,62989043.0,5578251.0,3863071.0,7738928.0,3656437.0,32639.0,5195509.0,10386234.0,30084.0,800370000.0,10362672.0,2632022.0,32639.0,5195509.0,800370000.0,62989043.0,2632022.0,10386234.0,10362672.0
Sep-14,65125922.0,5879693.0,4007376.0,7827858.0,3680580.0,36331.0,5162311.0,11418464.0,29383.0,815741000.0,10902810.0,2532990.0,36331.0,5162311.0,815741000.0,65125922.0,2532990.0,11418464.0,10902810.0
Dec-14,72143203.0,6234801.0,4304716.0,8622731.0,4028141.0,44050.0,5801992.0,11590259.0,29567.0,793375000.0,11782630.0,2769806.0,44050.0,5801992.0,793375000.0,72143203.0,2769806.0,11590259.0,11782630.0
Mar-15,75101185.0,6485965.0,4652083.0,8708471.0,4195180.0,42604.0,6468224.0,12527134.0,28992.0,831948000.0,12951305.0,2940196.0,42604.0,6468224.0,831948000.0,75101185.0,2940196.0,12527134.0,12951305.0
Jun-15,74436162.0,6705305.0,4800824.0,9018796.0,4390633.0,44652.0,6190710.0,12661961.0,26922.0,859299000.0,13121290.0,3336096.0,44652.0,6190710.0,859299000.0,74436162.0,3336096.0,12661961.0,13121290.0
Sep-15,88043173.0,7203697.0,4742143.0,9029276.0,4534420.0,50827.0,6403585.0,13498964.0,23549.0,931562000.0,14289917.0,3200273.0,50827.0,6403585.0,931562000.0,88043173.0,3200273.0,13498964.0,14289917.0
Dec-15,90176234.0,7818528.0,5112040.0,10695862.0,4609720.0,55040.0,6894061.0,13274827.0,22101.0,900135000.0,14261541.0,3332050.0,55040.0,6894061.0,900135000.0,90176234.0,3332050.0,13274827.0,14261541.0
Mar-16,80248015.0,7952394.0,4903861.0,9386007.0,4532264.0,50545.0,7030226.0,13233281.0,22148.0,859160000.0,13458854.0,3352529.0,50545.0,7030226.0,859160000.0,80248015.0,3352529.0,13233281.0,13458854.0
Jun-16,76656712.0,8000303.0,5067845.0,9132232.0,4862604.0,52589.0,6770607.0,13078038.0,22504.0,818332000.0,13048678.0,3230528.0,52589.0,6770607.0,818332000.0,76656712.0,3230528.0,13078038.0,13048678.0
Sep-16,79110196.0,7911383.0,5079217.0,9304020.0,4948775.0,60240.0,6538505.0,13045707.0,21065.0,803206000.0,13634825.0,3439389.0,60240.0,6538505.0,803206000.0,79110196.0,3439389.0,13045707.0,13634825.0
Dec-16,83841418.0,8104030.0,5525143.0,10529884.0,4923865.0,46246.0,6676133.0,13565197.0,20052.0,804945000.0,13509331.0,3137379.0,46246.0,6676133.0,804945000.0,83841418.0,3137379.0,13565197.0,13509331.0
Mar-17,80733942.0,8255151.0,5931818.0,10857207.0,4875883.0,47551.0,6596669.0,13958137.0,19411.0,788046000.0,13446033.0,3085625.0,47551.0,6596669.0,788046000.0,80733942.0,3085625.0,13958137.0,13446033.0
Jun-17,84124011.0,8227507.0,6217840.0,11743163.0,5061637.0,46198.0,6389512.0,13647784.0,18772.0,808054000.0,14181424.0,3082148.0,46198.0,6389512.0,808054000.0,84124011.0,3082148.0,13647784.0,14181424.0
Sep-17,83020423.0,8641026.0,6676597.0,13049451.0,5266231.0,44991.0,6932398.0,14140543.0,19084.0,803870000.0,13964453.0,3715446.0,44991.0,6932398.0,803870000.0,83020423.0,3715446.0,14140543.0,13964453.0
Dec-17,86851989.0,9330722.0,6676000.0,12553676.0,5700068.0,47627.0,6453521.0,14270404.0,18438.0,831515000.0,13985987.0,3677691.0,47627.0,6453521.0,831515000.0,86851989.0,3677691.0,14270404.0,13985987.0
Mar-18,82378945.0,9736075.0,6980567.0,13376182.0,5694754.0,45632.0,6137216.0,14717512.0,17748.0,824153000.0,14526053.0,3805319.0,45632.0,6137216.0,824153000.0,82378945.0,3805319.0,14717512.0,14526053.0
Jun-18,90921356.0,9855215.0,6917997.0,14322715.0,6307220.0,45661.0,8235356.0,16000094.0,15150.0,850282000.0,15464046.0,3898363.0,45661.0,8235356.0,850282000.0,90921356.0,3898363.0,16000094.0,15464046.0
Sep-18,95691043.0,10033057.0,7970002.0,15874697.0,6741180.0,43124.0,8077613.0,16774608.0,15020.0,866756000.0,16274130.0,4131570.0,43124.0,8077613.0,866756000.0,95691043.0,4131570.0,16774608.0,16274130.0
Dec-18,94126138.0,9696399.0,7763425.0,14530566.0,6490161.0,45866.0,7853743.0,18554580.0,14915.0,860473000.0,15399850.0,4038785.0,45866.0,7853743.0,860473000.0,94126138.0,4038785.0,18554580.0,15399850.0
Mar-19,96905532.0,10164903.0,8013828.0,14705816.0,7175323.0,40190.0,8235316.0,19427202.0,14891.0,949087000.0,15226982.0,4233195.0,40190.0,8235316.0,949087000.0,96905532.0,4233195.0,19427202.0,15226982.0
Jun-19,98738979.0,10730795.0,7764578.0,15400452.0,8619739.0,37558.0,7645215.0,23637176.0,14703.0,965248000.0,14907806.0,4101599.0,37558.0,7645215.0,965248000.0,98738979.0,4101599.0,23637176.0,14907806.0
Sep-19,102475317.0,10398992.0,7935226.0,18446750.0,8468089.0,32643.0,7837261.0,23702107.0,14327.0,924465000.0,15479421.0,4334798.0,32643.0,7837261.0,924465000.0,102475317.0,4334798.0,23702107.0,15479421.0

In [16]:
stocks

ticker         WEGE3         WEGE4
Date
Dec-91  5.522262e+01  5.522262e+01
Mar-92  1.030606e+02  1.030606e+02
Jun-92  1.844668e+02  1.844668e+02
Sep-92  3.521265e+02  3.521265e+02
Dec-92  6.858575e+02  6.858575e+02
Mar-93  1.488662e+03  1.488662e+03
Jun-93  3.234225e+03  3.234225e+03
Sep-93  7.472003e+03  7.472003e+03
Dec-93  1.942920e+04  1.942920e+04
Mar-94  5.741367e+04  5.741367e+04
Jun-94  1.870886e+05  1.870886e+05
Sep-94  2.132182e+05  2.132182e+05
Dec-94  2.357480e+05  2.357480e+05
Mar-95  2.677270e+05  2.677270e+05
Jun-95  2.964190e+05  2.964190e+05
Sep-95  3.407340e+05  3.407340e+05
Dec-95  3.617490e+05  3.617490e+05
Mar-96  4.086030e+05  4.086030e+05
Jun-96  4.364540e+05  4.364540e+05
Sep-96  4.736360e+05  4.736360e+05
Dec-96  4.948700e+05  4.948700e+05
Mar-97  5.015860e+05  5.015860e+05
Jun-97  5.618470e+05  5.618470e+05
Sep-97  5.853240e+05  5.853240e+05
Dec-97  6.107730e+05  6.107730e+05
Mar-98  6.395850e+05  6.395850e+05
Jun-98  7.000390e+05  7.000390e+05
Sep-98  7.225200e+05  7.225200e+05
Dec-98  7.781970e+05  7.781970e+05
Mar-99  9.161140e+05  9.161140e+05
...              ...           ...
Jun-12  9.109705e+06  9.109705e+06
Sep-12  8.757033e+06  8.757033e+06
Dec-12  8.873550e+06  8.873550e+06
Mar-13  9.496435e+06  9.496435e+06
Jun-13  9.542922e+06  9.542922e+06
Sep-13  9.552065e+06  9.552065e+06
Dec-13  1.014129e+07  1.014129e+07
Mar-14  9.898693e+06  9.898693e+06
Jun-14  1.036267e+07  1.036267e+07
Sep-14  1.090281e+07  1.090281e+07
Dec-14  1.178263e+07  1.178263e+07
Mar-15  1.295130e+07  1.295130e+07
Jun-15  1.312129e+07  1.312129e+07
Sep-15  1.428992e+07  1.428992e+07
Dec-15  1.426154e+07  1.426154e+07
Mar-16  1.345885e+07  1.345885e+07
Jun-16  1.304868e+07  1.304868e+07
Sep-16  1.363482e+07  1.363482e+07
Dec-16  1.350933e+07  1.350933e+07
Mar-17  1.344603e+07  1.344603e+07
Jun-17  1.418142e+07  1.418142e+07
Sep-17  1.396445e+07  1.396445e+07
Dec-17  1.398599e+07  1.398599e+07
Mar-18  1.452605e+07  1.452605e+07
Jun-18  1.546405e+07  1.546405e+07
Sep-18  1.627413e+07  1.627413e+07
Dec-18  1.539985e+07  1.539985e+07
Mar-19  1.522698e+07  1.522698e+07
Jun-19  1.490781e+07  1.490781e+07
Sep-19  1.547942e+07  1.547942e+07

[112 rows x 2 columns]

In [218]:
# queremos remover os vizinhos de NAs coluna a coluna
# estou com o problema de contar o numero máximo de consecutive non NA
# https://stackoverflow.com/questions/41968892/counting-consecutive-numbers-in-a-list
# https://stackoverflow.com/questions/44337512/delete-non-consecutive-values-from-a-dataframe-column
# https://stackoverflow.com/questions/52671308/counting-the-number-of-consecutive-values-that-meets-a-condition-pandas-datafra
# http://blog.adeel.io/2016/10/30/removing-neighboring-consecutive-only-duplicates-in-a-pandas-dataframe/
# talvez a melhor maneira de lidar com um shift seja direto no df, sem passar por series
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.shift.html
# True & False # dá False
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.shift.html
sh_plus = tot_ass.shift(periods=1)
sh_minus = tot_ass.shift(periods=-1)
tot_ass[sh_plus.isnull()&sh_minus.isnull()] = np.NAN

In [222]:
tot_ass.to_excel("output.xlsx")

In [195]:
True & False

NameError: name 'T' is not defined

In [178]:
serie
s_plus = serie.shift()
s_minus = serie.shift(periods=-1)

# periods=1

In [183]:
s_plus.values == 2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [209]:
# criar df com dictionary e um index e usar expressões lógicas
df1 = pd.DataFrame({'A': [True, False, True, False],
                    'B': [False, True, False, True],
                    'C': [False, False, True, False],
                    'D': [False, False, True, False]},
                    index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': [True, False, False, False],
                    'B': [True, False, False, False],
                    'C': [True, True, True, True],
                    'D': [False, False, False, False]},
                    index=[0, 1, 2, 3])
df3 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])
df1&df2
df1|df2
df3[df1&df2] = np.NAN

In [212]:
df3.isnull()

       A      B      C      D
0   True  False  False  False
1  False  False  False  False
2  False  False   True  False
3  False  False  False  False

In [203]:
df1&df2

       A      B      C      D
0   True  False  False  False
1  False  False  False  False
2  False  False   True  False
3  False  False  False  False

In [200]:
df1|df2

       A      B     C      D
0   True   True  True  False
1  False   True  True  False
2   True  False  True   True
3  False   True  True  False

In [208]:
ttt = np.NAN